### PR TITLE
Green sustainability

### PR DESCRIPTION
**Pull request by zflamig**
*Issue #, if available:*

*Description of changes:*
feat(sustainability): Sustainability tags green
feat(tags): Sorted alphabetically
feat(docker): Added for dev

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jflasher** [comment]
Assigning to @jedsundwall to review the tag coloring changes. @zflamig can you add a screenshot of what it looks like with the new coloring?

**Comment by zflamig** [comment]
Screen Shot 2019-08-01 at 11 16 33 AM

**Comment by jedsundwall** [comment]
Please change the color of the tag to #1e8900 and the hover-state color to #6aaf35 which are shades of green from AWS' branding palette. 

FWIW, I'm ambivalent about this change. It looks cool, and I like the sentiment behind it, but we shouldn't convey information with mere color changes. Let's go ahead and do this though. I'd like us to consider using tiny icons or sprites for "special" tags in the future.

**Comment by zflamig** [comment]
Updated the colors. I agree with the idea there. We can think how to make that work and which tags to do it for in the future.

**Pull request merged**
